KISSY.add("itempub/mvc",function(a){function v(d){this.namespace=d}function s(d){d+="";return d.charAt(0).toUpperCase()+d.substring(1)}a.log("mvc is started");var w=a.DOM,f=a.JSON,b=new a.Base;a.augment(v,{set:function(d,c){var g=this;a.isObject(d)?a.each(d,function(h,q){g.set(q,h)}):b.set(g.namespace+":"+d,c)},get:function(d){return b.get(this.namespace+":"+d)},onDataChange:function(d,c){function g(){var j=[],k;try{a.each(d,function(u){u=b.get(u);if(a.isUndefined(u)||a.isNull(u))throw"datadeletion";
j.push(u)})}catch(l){return}(k=c.apply(q.control,j))&&q.set(k)}var h=[],q=this;if(a.isUndefined(d))c.apply(q.control);else{if(a.isString(d))d=[d];a.each(d,function(j,k){if(j.indexOf(":")===-1)j=d[k]=q.namespace+":"+j;h.push("after"+s(j)+"Change")});b.on(h.join(" "),g);g()}}});var i=function(d){this.model=d};a.augment(i,{getData:function(d){this.model.set(f.parse(w.html(d)))},update:function(d,c){this.model.set(d,c)},use:function(d){this.model.onDataChange(d.need,d.run)}});var e=function(d){if(b[d])a.log("namespace"+
d+"is used!");else{b[d]=true;this.model=new v(d);this.model.control=this;this.view=new i(this.model)}};a.augment(e,i);a.log("mvc is ok");a.log(["pipeData:",b.__attrVals]);return e});
KISSY.add("itempub/upload/imgpreview",function(a){function v(f){var b=document.createElement("div");b.style.cssText=';width:1px;height:1px;position:absolute;left:-9999px;top:-9999px;filter:progid:DXImageTransform.Microsoft.AlphaImageLoader(sizingMethod="image",src="'+f+'")';document.body.appendChild(b);f={height:b.offsetHeight,width:b.offsetWidth};b.parentNode.removeChild(b);a.log(f);return f}function s(f){this.cfg=f||{}}var w;a.augment(s,{pvSupported:true,_oldResizeImg:function(f,b){var i=this;if(!b)if(f.complete)b=
f;else{f.onload=function(){i._oldResizeImg(f,f)};return}var e=this.cfg.maxWidth||0,d=this.cfg.maxHeight||0,c=b.height;b=b.width;var g=c/b;if(c>d){c=d;b=d/g}if(b>e){b=e;c=e*g}f.style.width=b+"px";f.style.height=c+"px"},_resizeImg:a.UA.ie===6?function(f){this._oldResizeImg(f)}:function(f){var b=this.cfg;if(b.maxWidth){f.style.width="auto";f.style.maxWidth=b.maxWidth+"px"}if(b.maxHeight){f.style.height="auto";f.style.maxHeight=b.maxHeight+"px"}},previewByUrl:function(f,b){var i=new Image;this._resizeImg(i);
i.src=f;b(i)},preview:function(f,b){var i=f.files,e=i&&(i=i[0]),d=this.constructor.prototype,c=a.UA.ie;if(e&&window.FileReader)d.preview=function(g,h){var q=new FileReader,j=this;q.onload=function(k){j.previewByUrl(k.target.result,h)};q.onerror=function(){j._notSupport(g,h)};q.readAsDataURL(g.files[0])};else if(e&&i.getAsDataURL)d.preview=function(g,h){this.previewByUrl(g.files[0].getAsDataURL(),h)};else if(c>6&&c<9){w=c>7?"data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==":
"http://img01.taobaocdn.com/tps/i1/T1M8CjXf8lXXXXXXXX-1-1.gif";d.preview=function(g,h){var q,j;g.select();try{q=document.selection.createRange().text}catch(k){d.preview=this._notSupport;this.preview(g,h);return}finally{document.selection.empty()}j=v(q);g=new Image;g.src=w;this._oldResizeImg(g,j);g.style.filter='progid:DXImageTransform.Microsoft.AlphaImageLoader(sizingMethod="scale",src="'+q+'")';h(g)}}else d.preview=c===6?function(g,h){this.previewByUrl(g.value,h)}:this._notSupport;this.preview(f,
b)},_notSupport:function(f,b){var i=this.constructor.prototype;i.pvSupported=false;i._notSupport=function(e,d){e=e.value;var c;c=e.lastIndexOf("\\");if(c===-1)c=e.lastIndexOf("/");e=e.substr(c+1);c=document.createElement("ins");c.title=e;c.className="img";c.innerHTML=e;d(c,true)};this._notSupport(f,b)}});return s});
KISSY.add("itempub/upload/picmanager",function(a,v){function s(e){e.value="";if(e.value){a.log("use clear by reset");var d=e.nextSibling,c=e.parentNode,g=document.createElement("form");g.appendChild(e);g.reset();d?c.insertBefore(e,d):c.appendChild(e)}}function w(e,d){if(e){this.cfg=a.merge(d,i);this.container=e;this.itemLis=a.query(this.cfg.itemSel,e);this._initData();this._initEvent()}}var f=a.DOM,b=a.Event,i={itemSel:".pm-item",dataUrlSel:".J_PicUrl",picElSel:".preview",actSel:".act",sampleSel:".examp",
itemcont:".pm-itemcont"};a.augment(w,v,{_initData:function(){var e=this,d,c,g;a.each(this.itemLis,function(h,q){d=a.get(e.cfg.dataUrlSel,h);if(q===0){g=a.get(e.cfg.picElSel,h);c=g.innerHTML}if(d.value){e.update(h,d.value);if(c&&g)g.innerHTML+=c}})},_initEvent:function(){var e=this;b.on(this.container,"click",function(d){d=d.target;var c;if(c=d.getAttribute("data-act"))e[c](f.parent(d,e.cfg.itemSel))});b.on(this.itemLis,"mouseover",function(){var d=a.get(e.cfg.picElSel,this),c=a.get(e.cfg.actSel,this);
if(a.trim(d.innerHTML))c.style.display="block"});b.on(this.itemLis,"mouseout",function(){a.get(e.cfg.actSel,this).style.display="none"})},_changeCont:function(e,d){var c=f.get(this.cfg.itemcont,e),g=f.get(this.cfg.itemcont,d);e.appendChild(g);d.appendChild(c)},moveLeft:function(e){var d=f.prev(e);d&&this._changeCont(e,d)},moveRight:function(e){var d=f.next(e);d&&this._changeCont(e,d)},del:function(e){this.update(e)},add:function(e){var d,c=this,g,h,q;a.each(this.itemLis,function(j){if(h=a.get(c.cfg.dataUrlSel,
j))if(h.value===e){q=true;return false}g=a.get(c.cfg.itemcont,j);if(!g.getAttribute("data-picdata")){d=j;return false}});if(q)return{error:true,type:"exist"};else if(d){this.update(d,e);return{result:false}}else return{error:true,type:"overnum"}},loading:function(e,d){var c=f.parent(e,this.cfg.itemSel);if(d===1){f.addClass(c,"loading");this.disable(e)}else{f.removeClass(c,"loading");this.able(e)}},disable:function(e){a.log(["disable",e]);e=f.parent(e,this.cfg.itemcont);f.addClass(e,"pm-disabled")},
able:function(e){a.log(["able",e]);e=f.parent(e,this.cfg.itemcont);f.removeClass(e,"pm-disabled")},update:function(e,d,c){f.test(e,this.cfg.itemSel)||(e=f.parent(e,this.cfg.itemSel));e=a.get(this.cfg.itemcont,e);var g=a.get(this.cfg.dataUrlSel,e),h=a.get(this.cfg.picElSel,e),q=f.filter("input",function(j){return j.type==="file"},e)[0];if(d){a.log("preview");if(a.isString(d)){e.setAttribute("data-picdata","url");g.value=d;s(q);if(!c){h.innerHTML="";this.previewByUrl(d+"_100x100.jpg",function(j){h.appendChild(j)})}}else{e.setAttribute("data-picdata",
"form");g.value="";if(!c){h.innerHTML="";this.preview(d,function(j){h.appendChild(j)})}}f.addClass(e,"hasCont")}else{h.innerHTML="";e.setAttribute("data-picdata","");g.value="";s(q);f.removeClass(e,"hasCont")}},batchUpdateUrl:function(e){var d=0,c=this,g;a.each(this.itemLis,function(h){g=a.get(c.cfg.itemcont,h);g.getAttribute("data-picdata")==="form"&&c.update(h,e[d++],c.pvSupported)})},isLoading:function(){var e=false;a.each(this.itemLis,function(d){if(f.hasClass(d,"loading"))e=true});return e}});
return w},{requires:["./imgpreview"]});KISSY.add("itempub/upload/fileinfo",function(a){function v(s,w){var f,b,i;if(s.files&&(f=s.files[0])){i=f.name;f.extension=i.substr(i.lastIndexOf(".")+1);w(f)}else{f=s.value;b=f.lastIndexOf("\\");if(b===-1)b=f.lastIndexOf("/");i=f.substr(b+1);b=i.substr(i.lastIndexOf(".")+1).toLowerCase();f={name:i,extension:b};if("png|jpg|jpeg|bmp|gif".indexOf(b)!==-1&&a.UA.ie===6){b=new Image;b.onload=function(){f.size=this.fileSize;w(f)};b.src=s.value}else w(f)}}return v});
KISSY.add("itempub/upload/imgspace",function(a){function v(b,i){this.container=a.get(b);this.cfg=a.merge(f,i);this._init()}var s=a.DOM,w=a.Event,f={firstShow:null,use:["space"],frameSrc:"nTadget.html",modulesData:{space:"\u4ece\u56fe\u7247\u7a7a\u95f4\u9009\u62e9",insert:"\u63d2\u5165\u56fe\u7247"}};a.augment(v,a.EventTarget,{_init:function(){this._initBar();this.addModules(this.cfg.use);this.cfg.firstShow&&this.toggle(this.cfg.firstShow)},_initBar:function(){var b=this,i=document.createElement("div");i.className="imgSpaceBar";this.container.appendChild(i);
w.on(i,"click",function(e){e=e.target;s.hasClass(e,"J_Toggle")&&b.toggle(e.getAttribute("data-module"))});this.bar=i},_createFrame:function(){var b=document.createElement("iframe");b.setAttribute("frameBorder","0");b.className="picFrame";this.container.appendChild(b);return b},_initCont:function(b){var i=this;this.frame=a.get("picFrame",this.container)||this._createFrame();w.on(this.frame,"load",function(){i.modules=i.frame.contentWindow.TB.Sell.Modules.uploadSpace;i.modules.on("resize",function(e){i.frame.style.height=
e.height+"px"});i.modules.on("insert",function(e){i.fire("insert",e)});i.frame.style.height=i.frame.contentWindow.document.body.offsetHeight+10+"px";b.call(i)});this.frame.src=this.cfg.frameSrc},addModules:function(b){var i=this;b=a.isArray(b)?b:[b];a.each(b,function(e){var d=document.createElement("a");d.className="J_Toggle";d.setAttribute("data-module",e);d.innerHTML=i.cfg.modulesData[e];i.bar.appendChild(d)})},toggle:function(b){a.each(a.query(".J_Toggle",this.bar),function(i){i.getAttribute("data-module")===
b&&!s.hasClass(i,"expanded")?s.addClass(i,"expanded"):s.removeClass(i,"expanded")});this.frame?this.modules.toggle(b):this._initCont(function(){this.modules.toggle(b)})}});return v});
KISSY.add("itempub/upload/fileupload",function(a){var v=a.io,s={UPLOADCOMPLETE:"uploadComplete",UPLOADERROR:"uploadError"},w=function(f,b){this.inputs=a.isArray(f)?f:[f];this.cfg=b||{};this.form=this._createForm();this._temInputs=[]};a.augment(w,a.Event.Target,{_createForm:function(){var f=document.createElement("form");f.style.display="none";f.setAttribute("method","post");f.setAttribute("enctype","multipart/form-data");f.setAttribute("encoding","multipart/form-data");document.body.appendChild(f);
return f},_copyInputs:function(){var f=this;a.each(this.inputs,function(b,i){var e=b.nextSibling,d=b.parentNode;f._temInputs[i]=e?function(){d.insertBefore(b,e)}:function(){d.appendChild(b)};f.form.appendChild(b)})},_resume:function(){var f=this;a.each(f._temInputs,function(b,i){b();f._temInputs[i]=null})},upload:function(f){if(f)f=a.merge(f,this.cfg.data||{});var b=this,i=this.form;this._copyInputs();a.log(f);v({url:this.cfg.url,type:"post",dataType:"json",form:i,data:f,serializeArray:false,timeout:2E4,
success:function(e){a.log(["upload complete:",e]);e.success&&i.reset();b._resume();b.fire(s.UPLOADCOMPLETE,{data:e})},error:function(){a.log("xhr error");b._resume();b.fire(s.UPLOADERROR)},complete:function(){a.log("upload handle complete")}})}});return w});
KISSY.add("itempub/upload/itempic",function(a,v,s,w,f,b){function i(j){j.value="";if(j.value){a.log("use clear by reset");var k=j.nextSibling,l=j.parentNode,u=document.createElement("form");u.appendChild(j);u.reset();k?l.insertBefore(j,k):l.appendChild(j)}}function e(j,k){var l=c.get(".J_SubmitLoader");if(j){if(!l){l=c.create('<div class="submit-loader J_SubmitLoader">\u5b9d\u8d1d\u56fe\u7247\u4e0a\u4f20\u4e2d\uff0c\u8bf7\u7a0d\u540e\u2026</div>');(j=k?k.parentNode:c.get("div.submit"))&&j.appendChild(l)}c.show(l)}else c.hide(l)}a.log("itemPic is started");
var d=a.Event,c=a.DOM;v=new v("itemPic");var g={checkFile:{need:"file",run:function(j){if("png|jpg|jpeg|bmp|gif".indexOf(j.extension.toLowerCase())===-1)return this.update({error:{info:"\u8bf7\u9009\u62e9\u56fe\u7247!",file:j}});if(j.size&&j.size>5E5)return this.update({error:{info:"\u56fe\u7247\u5927\u5c0f\u4e0d\u80fd\u8d85\u8fc7500K\uff01",file:j}});this.update({fileVaildated:j})}}},h={init:{need:["picManagerWrap","tadgetWrap","picUploadApi","picTadgatSrc","data"],run:function(j,k,l,u,m){var r=c.filter("input",function(p){return p.type==="file"},j),n=this,o=new s(j,
{maxHeight:88,maxWidth:88});j=new f(k,{frameSrc:u,use:["space"]});a.each(r,function(p,t){var x=new b(p,{url:l,data:m});x.idx=t+1;x.on("uploadComplete",function(){});x.on("uploadError",function(){});p.__uploader=x});d.on(r,"change",function(p){a.log("change");this.value&&w(this,function(t){t.srcEl=p.target;n.update({file:t})})});j.on("insert",function(p){p=o.add(p.src);if(p.error){p.info=p.type=="exist"?"\u540c\u4e00\u5f20\u56fe\u7247\u4e0d\u80fd\u591a\u6b21\u6dfb\u52a0":p.type==="overnum"?"\u6700\u591a\u53ea\u80fd\u9009\u62e95\u5f20\u56fe\u7247":p.type;n.update({error:p})}});this.update({picManager:o})}},
fileChange:{need:["fileVaildated","picManager","picManagerWrap"],run:function(j,k){j=j.srcEl;k.update(j,j);setTimeout(function(){a.log("loading")},500)}},fileUploadXHRError:{need:["fileUploadXHRErrorData","picManager"],run:function(j,k){k.loading(j.el,0)}},fileUploadComplete:{need:["fileUploadCompleteData","picManager"],run:function(j,k){a.log(j);k.loading(j.el,0);var l=j.data;l.success&&k.update(j.el,l.picPath,k.pvSupported)}},error:{need:["error"],run:function(j){j.file&&j.file.srcEl&&i(j.file.srcEl);
alert(j.info)}}};v.init=function(){var j=this,k=c.get("#J_ModItemPic");if(k){j.getData(k);j.update({picManagerWrap:a.get(".pic-manager2"),tadgetWrap:a.get(".J_picTadget")});a.each(a.merge(g,h),function(l){j.use(l)})}};var q;v.valid=function(j,k){function l(){a.log("timer validate");if(u.isLoading())q=setTimeout(l,500);else{e(false,k);clearTimeout(q);j(true)}}q&&clearTimeout(q);var u=this.model.get("picManager");if(!u||!u.isLoading())j(true);else{e(true,k);l()}};a.log("itemPic is ok!");return v},{requires:["../mvc",
"./picmanager","./fileinfo","./imgspace","./fileupload"]});
KISSY.add("itempub/sku/basegroup",function(a){function v(f,b){s.prop(f,"disabled",b?false:true)}var s=a.DOM,w=function(){this.init.apply(this,arguments)};a.augment(w,a.EventTarget,{init:function(f){this.elGroup=f;this.isDisabled=s.hasClass(f,"disabled");this.elBox=s.get(".sku-box",f);this.formFields=s.query("input",f)},disable:function(){if(!this.isDisabled){v(this.formFields,false);s.addClass(this.elGroup,"disabled");this.isDisabled=true}},enable:function(){if(this.isDisabled){v(this.formFields,
true);s.removeClass(this.elGroup,"disabled");this.isDisabled=false}}});return w});
KISSY.add("itempub/sku/officialgroup",function(a,v){function s(d){var c=d.parentNode,g=b.get(".editbox",c);c=b.get(".labelname",c);var h=d.value;return{id:h.replace(":","-"),pv:h,alias:w(b.val(g)),name:w(b.text(c)),color:d.getAttribute("data-color"),imgThumb:d.getAttribute("data-thumb"),imgPath:d.getAttribute("data-path")}}function w(d){return d&&a.escapeHTML(d)}function f(d){d=b.query(".J_Checkbox",d);a.each(d,function(c){var g=b.parent(c,".sku-item");b[c.checked?"addClass":"removeClass"](g,"edit")})}
var b=a.DOM,i=a.Event,e=function(){e.superclass.constructor.apply(this,arguments)};a.extend(e,v,{init:function(d){e.superclass.init.apply(this,arguments);var c=b.attr(d,"data-caption"),g=b.attr(d,"data-features")||"list",h=b.hasClass(d,"required");this.type="OfficialGroup";this.caption=c;this.features=g;this.isRequired=h;this.fetchData();this._bindEvent()},hasFeature:function(d){return this.features.indexOf(d)!=-1},_bindEvent:function(){var d=this,c=d.elBox,g=d.hasFeature("edit");i.delegate(c,"click",
function(h){if(b.hasClass(h,"J_Checkbox")||b.hasClass(h,"J_CheckAll"))return true},function(h){h=h.currentTarget;var q=b.hasClass(d.elBox,"collapse"),j=d.fields,k=h.checked,l=[h];if(b.hasClass(h,"J_CheckAll")){l=b.filter(b.query(".J_Checkbox",c),function(u){return u.checked==!k&&!(q&&b.hasClass(b.parent(u,"li"),"hide"))});b.prop(l,"checked",k);l.push(h)}d.fetchData();if(d.fire("validBeforeSave")===false){b.prop(l,"checked",!k);d.fields=j}else{g&&f(c);d.fire("dataChanged")}});i.delegate(c,"blur",function(h){return h.type==
"text"&&b.hasClass(h,"editbox")},function(h){h=b.parent(h.target,"li");h=b.get(".J_Checkbox",h);h=s(h);d.fire("dataUpdated",{target:h})});i.on(b.get(".J_SKUMore",d.elGroup),"click",function(h){h.halt();d.expandGroup()})},expandGroup:function(){b.hasClass(this.elBox,"collapse")&&b.removeClass(this.elBox,"collapse")},fetchData:function(){this.fields=this.getDataFromNode()},getDataNode:function(){var d=this,c=d.elBox,g=b.hasClass(d.elBox,"collapse");return b.filter(".J_Checkbox",function(h){var q=b.parent(h,
"li");return!(g&&b.hasClass(q,"hide"))&&!d.isDisabled&&h.checked===true},c)},getDataFromNode:function(){var d=this.getDataNode(),c=[];a.each(d,function(g){c.push(s(g))});return c}});return e},{requires:["./basegroup"]});
KISSY.add("itempub/sku/customgroup",function(a,v,s){function w(k){var l=k.getAttribute("name").replace("prop_","");return{id:l,pv:l.replace("_",":"),name:f(k.value)}}function f(k){return k&&a.escapeHTML(k)}function b(k,l){k={caption:k.caption||d,pid:k.pid||q.getPropId(),fields:k.fields||[]};var u=k.fields;l=l.groupSize*1;for(var m=0;m<l;m++)u[m]||(k.fields[m]={vid:q.getValId(),name:""});return k}var i=a.DOM,e=a.Event,d="",c=0,g=0,h={SAVE:{disabled:false,writeable:true,text:"\u4fdd\u5b58"},EDIT:{disabled:false,
writeable:false,text:"\u7f16\u8f91"},AWAIT:{disabled:true,writeable:true,text:"\u4fdd\u5b58"}},q=function(){this.init.apply(this,arguments)},j={groupSize:10,listContainer:"#J_CustomSKUList",extensible:false,pid:0,vid:0};a.extend(q,v,{init:function(k,l){l=a.merge(j,l);k=b(k,l);var u=s('<div class="sku-group sku-custom"><label class="sku-label"><input maxlength="4" class="sku-caption text" pattern="^[^/$/^/:/;/,/./~/-/_]*$" patterninfo="\u683c\u5f0f\u8f93\u5165\u9519\u8bef" value="{{caption}}" name="prop_{{pid}}" type="text" />\uff1a</label><div class="sku-box"><ul class="sku-list">{{#each fields as it}}<li><input maxlength="10" class="text" pattern="^[^/$/^/:/;/,/./~/-/_]*$" patterninfo="\u683c\u5f0f\u8f93\u5165\u9519\u8bef" name="prop_{{pid}}_{{it.vid}}" value="{{it.name}}" type="text" /></li>{{/each}}</ul><div class="sku-custom-operations"><a href="javascript:void(0);" class="sku-delgroup J_SKUDelGroup" title="\u5220\u9664">\u5220\u9664</a><a href="javascript:void(0);" class="sku-enforce J_SKUApplyData">\u4fdd\u5b58</a></div></div></div>').render(k);
this.pid=k.pid;q.superclass.init.call(this,i.create(u),l);this.type="CustomGroup";this.isSaved=this.writeable=true;this.theChange={rebuild:false,items:{}};i.append(this.elGroup,l.listContainer);this.elCaption=i.get(".sku-caption",this.elGroup);this.btnApply=i.get(".J_SKUApplyData",this.elBox);this.caption=f(i.val(this.elCaption));this._bindEvent();this.fetchData();this.fields.length>0?this.setState(h.EDIT):this.setState(h.AWAIT)},_bindEvent:function(){function k(n){var o=l.theChange,p=true,t=i.hasClass(n,
"sku-caption"),x=t?l.caption:d,z=a.trim(n.value),y=w(n);y.context=t?"caption":"text";y.target=n;t||a.each(l.fields,function(A){if(A.id==y.id){x=A.name;return false}});n=x!=d&&z==d;if(!(x==d&&z!=d)&&!n)p=false;if(p)o.rebuild=true;else o.items[y.id]=y;o=a.trim(l.elCaption.value)!==d;p=a.some(r,function(A){return a.trim(A.value)!=d&&A!=l.elCaption});l.setState(o&&p?h.SAVE:h.AWAIT);l.isSaved=false}var l=this,u=l.elBox,m=l.btnApply,r=i.query("input.text",l.elGroup);a.each(r,function(n){var o;e.on(n,"valuechange",
function(p){o&&o.cancel();o=a.later(function(){k(p.target)},50)})});e.on(m,"click",function(n){n.halt();!i.hasClass(m,"disabled")&&!l.isDisabled&&l.buttonToggle()});e.on(i.get(".J_SKUDelGroup",u),"click",function(n){n.halt();if(confirm("\u60a8\u786e\u5b9a\u8981\u5220\u9664\u8be5\u9500\u552e\u5c5e\u6027\uff1f")){i.remove(l.elGroup);l.fire("remove");l.fire("dataChanged")}})},fetchData:function(){this.caption=f(a.trim(this.elCaption.value));this.fields=this.getDataFromNode()},getDataNode:function(){var k=this;return i.filter("input",function(l){return!k.isDisabled&&
l.type==="text"&&a.trim(l.value)!==d},k.elBox)},getDataFromNode:function(){var k=this.getDataNode(),l=[];a.each(k,function(u){l.push(w(u))});return l},buttonToggle:function(){this.writeable?this.dataApply():this.setState(h.SAVE)},setState:function(k){var l=this.btnApply,u=k.writeable,m=u?"removeClass":"addClass";i.text(l,k.text);i[k.disabled?"addClass":"removeClass"](l,"disabled");if(this.writeable!==u){i[m](l,"sku-btnedit");i[m](this.elGroup,"readonly");this.writeable=u;a.each(this.formFields,function(r){if(r.type==
"text")i.prop(r,"readonly",u?false:true)})}},dataApply:function(){var k=this.theChange;if(this.fire("validBeforeSave")!==false){if(k.rebuild){this.fetchData();this.fire("dataChanged")}else{this.caption=this.elCaption.value;this.fire("dataUpdated",{items:k.items})}this.theChange={rebuild:false,items:{}};this.setState(h.EDIT);this.isSaved=true}},hasSaved:function(){return this.isDisabled||this.isSaved},focus:function(){try{this.elCaption.focus()}catch(k){}},fetchCPVId:function(){var k=[],l=this.pid,
u;this.fetchData();if(this.caption!==d){a.each(this.fields,function(m){k.push(m.pv.replace(l+":",d))});u=k.length>0?l+":"+k.join(","):d}else u=d;return u}});a.mix(q,{setInitializePV:function(k,l){k&&(c=k);l&&(g=l)},getPropId:function(){c-=1;return c},getValId:function(){g-=1;return g}});return q},{requires:["./basegroup","template"]});
KISSY.add("itempub/sku/imagetable",function(a,v){function s(c){return w(b.query(".J_Checkbox",c))}function w(c){var g=[];a.each(c,function(h){var q=h.parentNode,j=b.get(".editbox",q);q=b.get(".labelname",q);var k=h.value;g.push({id:k.replace(":","-"),pv:k,alias:f(b.val(j)),name:f(b.text(q)),color:h.getAttribute("data-color"),imgThumb:h.getAttribute("data-thumb"),imgPath:h.getAttribute("data-path")})});return g}function f(c){return c&&a.escapeHTML(c)}var b=a.DOM,i=a.Event,e={imgRequired:false},d=function(){this.init.apply(this,
arguments)};a.augment(d,a.EventTarget,{init:function(c,g){this.skuGroup=c;this.cfg=a.merge(e,g);this._buildTable()},_buildTable:function(){var c=this.skuGroup,g=c.caption,h=s(c.elGroup),q=a.some(h,function(j){return j.imgThumb&&j.imgPath});g={caption:g,imgRequired:this.cfg.imgRequired,hasImg:q};g=v('<table border="0" cellspacing="0" class="J_SKUImgTable img-table" style="display:none;"><caption>\u989c\u8272\u5c5e\u6027\u56fe\u7247\u4e0a\u4f20\u8868\u683c</caption><thead><tr><th>{{caption}}</th><th>\u56fe\u7247\uff08{{#if imgRequired}}\u5fc5\u987b\u4e0a\u4f20\u8be5\u989c\u8272\u5bf9\u5e94\u56fe\u7247{{#else}}\u65e0\u56fe\u7247\u53ef\u4e0d\u586b{{/if}}\uff09</th>{{#if hasImg}}<th>\u5df2\u6709\u56fe\u7247</th>{{/if}}</tr></thead><tbody></tbody></table>').render(g);
g=b.create(g);c=b.get(".sku-box",c.elGroup);this.tbody=b.get("tbody",g);this.table=g;this._buildTrs(h,q);b.append(g,c);this._bindEvent()},_buildTrs:function(c,g){var h=document.createDocumentFragment(),q=["transparent","assortment"];a.each(c,function(j){var k=a.inArray(j.color,q)?'<i class="color-lump color-{color}"></i>':'<i class="color-lump" style="background-color:#{color};"></i>';j.lump=a.substitute(k,{color:j.color});j={item:j,hasImg:g};j=v('<tr id="J_MapImg_{{item.id}}"><td class="tile">{{item.lump}}<span class="J_Map_{{item.id}}">{{item.alias || item.name}}</span></td><td><input type="file" name="cpvf_{{item.pv}}" /></td>{{#if hasImg}}<td class="preview">{{#if item.imgThumb && item.imgPath}}<input type="hidden" name="cpvf_old_{{item.pv}}" value="{{item.imgPath}}" /><a target="_blank" href="{{item.imgThumb}}"><img src="{{item.imgThumb}}_24x24.jpg" /></a><a class="del" href="javascript:void(0);">\u5220\u9664</a><a class="undel" data-path="{{item.imgPath}}" href="javascript:void(0);">\u6062\u590d\u5220\u9664</a>{{#else}}\u5f53\u524d\u65e0\u56fe\u7247{{/if}}</td>{{/if}}</tr>').render(j);
j=b.create(j);h.appendChild(j)});this.tbody.appendChild(h)},_bindEvent:function(){i.delegate(this.tbody,"click","a",function(c){c.halt();c=c.target;var g=b.parent(c,"td"),h=b.get("input",g);if(b.hasClass(c,"del")){h.value="";b.addClass(g,"deled")}else if(b.hasClass(c,"undel")){h.value=c.getAttribute("data-path");b.removeClass(g,"deled")}})},toggle:function(){var c=this.skuGroup.fields,g=this.table,h=this.tbody;if(c.length===0)b.hide(g);else{b.hide(b.query("tr",h));a.each(c,function(q){(q=b.get("#J_MapImg_"+
q.id))&&b.show(q)});b.show(g)}}});return d},{requires:["template"]});
KISSY.add("itempub/sku/lap",function(a){function v(c,g){if(c.length===0)this.isStop||a.each(this.callbacks,function(h){h()});else setTimeout(function(){s(c,g)},0)}function s(c,g){var h=+new Date+g.duration,q=-1;do{var j=c.shift();g.doIndex++;q++;a.each(g.handlers,function(k){k(j,g.doIndex,q)})}while(c.length>0&&h>+new Date&&!g.isPause);a.each(g.batchs,function(k){k(g.doIndex)});if(!(g.isPause&&c.length>0))if(c.length>0)setTimeout(function(){s(c,g)},g.delay);else{g.isStop=true;a.each(g.callbacks,function(k){k()})}}
function w(c,g){g=a.merge(b,g);c={data:[].concat(c),doIndex:-1,isFinish:false,callbacks:[],handlers:[],batchs:[]};return a.merge(g,c,d)}var f=false,b={duration:300,delay:50},i=[],e=null,d={handle:function(c){this.handlers.push(c)},batch:function(c){this.batchs.push(c)},then:function(c){this.callbacks.push(c)},start:function(){var c=this,g=c.data;if(f)i.push(c);else{f=true;e=i.shift()||c;c.then(function(){f=false;i[0]&&i[0].start()});v(g,c);c.start=function(){if(c.isPause){c.isPause=false;v(g,c)}}}},
pause:function(){this.isPause=true},stop:function(){this.isStop=true;this.data.length=0;this.isPause&&a.each(this.callbacks,function(c){c()})}};return w});
KISSY.add("itempub/sku/combotable",function(a,v,s){function w(m,r,n,o){return(new Function("groups","combo","defCombo",f(m,o)))(m,r,n)}function f(m,r){var n=[],o=[],p=[],t=[],x=[],z=m.length,y=r.region;n.push("var list = [];\n");a.each(m,function(A,B){var E=a.reduce(m.slice(B+1),function(C,D){return C*D.fields.length},1);n.push("KISSY.each(groups[",B,"].fields, function(it",B,") {\n");n.push("var item = it",B,', lump = "";');n.push("item.size=",E,";\n");n.push("if(item.color) {");n.push("var lumpStruct = KISSY.inArray(item.color, ['",
q.join("','"),"']) ? '",g,"' : '",h,"';\n");n.push("lump = KISSY.substitute(lumpStruct, {color: item.color});");n.push("}\n");n.push("item.lump=lump;");x.push('{caption:"'+A.caption.replace("\\","\\\\")+'", id:'+(A.pid||0)+"}");t.push("it"+B+".pv");p.push("it"+B);if(B==z-1){n.push("var id=[",t.join(),'].join(";");\n');n.push("list.push({\n");n.push("id: id, index: list.length, ",y?'priceLimit: "'+y+'", ':"","data: KISSY.merge(defCombo, combo[id]), items:[",p.join(),"]\n");n.push("});\n")}o.push("});\n")});
n=n.concat(o);n.unshift("var captions=[",x.join(),"];\n");n.push("return {list: list, captions: captions}");return n.join("")}function b(m,r){u&&u.stop();if(u)a.later(function(){b(m,r)},10);else{r.config=j;m.innerHTML=v(d).render(r);var n=i.get("table",m),o=document.createDocumentFragment(),p=i.get("tbody",n);i.scrollTop(m,0);u=s(r.list,{duration:j.duration});u.handle(function(t){t=v(c).render({it:t,config:r.config});o.appendChild(i.create(t))});u.batch(function(t){p.appendChild(o);i.css(n,"visibility",
"visible");i.removeClass(m,"sku-loading");t>k&&u.pause()});u.then(function(){p.appendChild(o);u=null});u.start()}}var i=a.DOM,e=a.Event,d='<table border="0" cellspacing="0" style="visibility:hidden;"><caption>\u9500\u552e\u5c5e\u6027\u5339\u914d\u8868</caption><thead><tr>{{#each captions as caption}}<th class="J_Map_{{caption.id}}">{{caption.caption}}</th>{{/each}}{{#if config.showPrice}}<th>\u4e00\u53e3\u4ef7<em>*</em></th>{{/if}}<th>\u5546\u5bb6\u7f16\u7801<em>*</em></th><th>\u4fdd\u9669\u7b80\u4ecb</th></tr></thead><tbody></tbody></table>',c='<tr>{{#each it.items as item}}{{#if it.index % item.size == 0}}<td rowspan="{{item.size}}" {{#if item.color}}class="tile"{{/if}}>{{item.lump}}<span class="J_Map_{{item.id}}">{{item.alias || item.name}}</span></td>{{/if}}{{/each}}{{#if config.showPrice}}<td class="price"><input type="hidden" name="{{it.id}}:id" value="{{it.data.skuid}}" /><input data-id="{{it.id}}" class="J_MapPrice text" data-type="price" type="money" name="{{it.id}}:p" value="{{it.data.price}}" required />{{#if config.isDistribution && it.data.region}}<span class="sku-limit">{{#if it.data.region.indexOf("-") == -1}}(\u89c4\u5b9a\u552e\u4ef7\uff1a{{it.data.region}} \u5143) {{#else}}(\u533a\u95f4\uff1a{{it.data.region}} \u5143){{/if}}</span>{{/if}}</td>{{/if}}<td class="productid"><input data-id="{{it.id}}" class="J_MapProductid text" data-type="tsc" type="text" name="{{it.id}}:tsc" value="{{it.data.tsc}}" required /></td><td class="intro"><textarea data-id="{{it.id}}" class="text textarea" data-type="insIntro" type="text" name="{{it.id}}:intro" maxlength="100" cols="20">{{it.data.insIntro}}</textarea></td></tr>',
g='<i class="color-lump color-{color}"></i>',h='<i class="color-lump" style="background-color:#{color};"></i>',q=["transparent","assortment"],j={isDistribution:false,showPrice:true,delay:200,duration:300},k=30,l,u;return a.mix({init:function(m,r){l=a.get(m);j=a.merge(j,r);this._bindEvent()},_bindEvent:function(){function m(){u&&u.start()}var r=this;e.delegate(l,"blur","input",function(n){r.fire("comboChanged",{target:n.target})});e.on(l,"scroll",a.buffer(m,j.delay))},render:function(m,r,n,o){var p=
l.parentNode;m=w(m,r,n,o);r=m.list.length;this.fire("adapter",{renderData:m});if(r===0)i.hide(p);else{i.addClass(l,"sku-loading");i.width(l,650);i.show(p);b(l,m)}}},a.EventTarget)},{requires:["template","./lap"]});
KISSY.add("itempub/sku/datacenter",function(a){function v(c){var g=[],h=[],q=[],j=true;a.each(c,function(k){if(k!==undefined){var l=k.fields.length,u=a.trim(k.caption);l=l>0&&u!==s;if(j&&!l)j=false;k.isRequired||l?h.push(k):q.push(k);if(k.isRequired||l)g.push(k)}});if(d.suitable&&h.length>0&&!j)g=[];return{combo:g,selected:h,invalid:q}}var s="",w={},f={},b=[],i={},e={},d={suitable:true};return a.mix({init:function(c){d=a.merge(d,c)},dataChange:function(){e=v(b);this.fire("dataChanged",{groups:e})},
setDefault:function(c,g){if(g!=undefined)w[c]=g},getDefault:function(c){return c?w[c]:w},setCombo:function(c,g){f[c]||(f[c]=g)},getCombo:function(c){return c?f[c]:f},setRender:function(c){i=c},getRender:function(){return i},updateRender:function(c,g){if(!(!c||c.length===0)){c=a.makeArray(c);var h=a.indexOf(g,e.combo);a.each(i.list,function(q){var j=q.id.split(";");a.each(c,function(k){if(j[h]==k.pv){q.items[h].alias=k.alias||k.name;return false}})})}},updatePrice:function(c){var g=this;a.each(i.list,
function(h){var q=h.data;if(q.price===s){q.price=c;g.getCombo(h.id).price=c}})},removeGroup:function(c){b[c.index]=undefined},getGroups:function(){return b},addGroup:function(c){c.index=b.length;b.push(c)},getSortGroups:function(){return v(b)}},a.EventTarget)});
KISSY.add("itempub/sku/manager",function(a,v,s,w,f,b){function i(m){m||alert("\u60a8\u7684\u9500\u552e\u5c5e\u6027\u7684\u7ec4\u5408\u8d85\u8fc7600\u7ec4\uff0c\u4f1a\u5bfc\u81f4\u9875\u9762\u6027\u80fd\u95ee\u9898\uff0c\u8bf7\u9002\u91cf\u5220\u51cf\u81f3600\u7ec4\u4ee5\u4e0b\u3002")}function e(){INS.Form&&INS.FormPostip&&INS.FormPostip.reposAllTip()}function d(m){var r=b.getGroups();return a.reduce(r,function(n,o){if(!o)return n;o=(!o.isDisabled&&o==m?o.getDataNode():o.fields).length;return o>0?n*o:n},1)<=k}function c(m,r,n){var o=new s(r,n);o.on("dataChanged",function(){b.dataChange()});o.on("validBeforeSave",function(){var p=d(o);i(p);return p});o.on("dataUpdated",
function(p){var t=[];a.each(p.items,function(x){var z=h.query(".J_Map_"+x.id,m),y=a.escapeHTML(x.target.value);z.length>0&&h.html(z,y);if(x.context!=="caption"){x.alias=y;t.push(x)}});b.updateRender(t,this)});o.on("remove",function(){b.removeGroup(this)});b.addGroup(o)}function g(m,r){if(r){var n=[];a.each(r,function(o,p){o.key=p;n.push(a.substitute('<input type="hidden" name="{key}:id:old" value="{skuid}" /><input type="hidden" name="{key}:p:old" value="{price}" /><input type="hidden" name="{key}:q:old" value="{quantity}" /><input type="hidden" name="{key}:tsc:old" value="{tsc}" />',
o))});n.unshift('<div id="defaultSKUHidden" style="display:none;">');n.push("</div>");h.append(h.create(n.join("")),m)}}var h=a.DOM,q=a.Event,j=null,k=600,l=4,u=function(){var m=[],r=b.getGroups();a.each(r,function(n){n&&n.type==="CustomGroup"&&m.push(n.fetchCPVId())});return m.join(";")};return{init:function(m,r){var n=r.config;this.buildOfficialGroup(m,n);this.buildCustomGroup(m,r.groups,n);n.isDistribution=!!r.distribution;this.initComboTable(h.get("#J_SKUMapContainer"),n);this.initDataCenter(r,
n);g(m,r.combo)},buildOfficialGroup:function(m,r){var n=h.query(".sku-group",m);a.each(n,function(o){var p=new v(o);if(p.hasFeature("image")){p.ImageTable=new w(p,r);p.ImageTable.toggle()}p.on("dataUpdated",function(t){t=t.target;var x=h.query(".J_Map_"+t.id,m);if(x.length!==0){h.html(x,t.alias||t.name);b.updateRender(t,this)}});p.on("dataChanged",function(){this.ImageTable&&this.ImageTable.toggle();b.dataChange()});p.on("validBeforeSave",function(){var t=d(p);i(t);return t});b.addGroup(p);r.suitable&&
l--})},buildCustomGroup:function(m,r,n){s.setInitializePV(n.MAX_PID,n.MAX_VID);a.each(r,function(o){c(m,o,n)})},initComboTable:function(m,r,n){f.init(m,r,n);f.on("adapter",function(o){o=o.renderData;a.each(o.list,function(p){b.setCombo(p.id,p.data)});b.setRender(o);a.all("#J_SKUMapContainer input").each(function(p){INS.Form.removeFieldElem(p[0])})});f.on("comboChanged",function(o){o=o.target;var p=o.getAttribute("data-id"),t=o.getAttribute("data-type"),x=b.getCombo()[p];x[t]=o.value;b.setCombo(p,
x);t==="quantity"&&this.fire("quantityChanged");t==="price"&&this.fire("priceChanged");INS.Form.addFieldElem(o);INS.Form.handleBlur(o)})},initDataCenter:function(m,r){var n=m.distribution||{};b.init(r);b.setDefault("skuid","0");b.on("dataChanged",function(o){o=o.groups.combo;var p=this.getCombo(),t=this.getDefault();f.render(o,p,t,n);e()});b.on("dataChanged",function(o){var p=o.groups,t=p.selected.length>=4?true:false;a.each(p,function(x){a.each(x,function(z){z[a.inArray(z,p.invalid)&&t?"disable":
"enable"]()})})});a.each(m.combo,function(o,p){b.setCombo(p,o)});if(m.distribution){b.setDefault("caiGouPrice",m.distribution.defaultCaiGouPrice);b.setDefault("region",m.distribution.defaultRegion)}b.dataChange()},bindAvaialCPVS:function(m){var r=u;u=function(){var n=r();m.value=n}},bindAddGroup:function(m,r,n){function o(){return h.query("div.sku-custom","#J_CustomSKUList").length>=l}function p(t){var x=t?"addClass":"removeClass";h.prop(m,"disabled",t);h[x](m,"disabled")}q.on(m,"click",function(){c(r,
{},n);var t=o();p(t);t=a.all("#J_CustomSKUList .sku-group");t.item(t.length-1).all("input").each(function(x){INS.Form.addFieldElem(x[0])});e()});b.on("dataChanged",function(t){t=t.groups.selected.length>=4?true:o();p(t)});a.UA.ie===6&&q.on(m,"mouseenter mouseleave",function(t){h[t.type==="mouseenter"?"addClass":"removeClass"](this,"hover")})},bindPrice:function(m){function r(n){b.setDefault("price",n)}q.on(m,"blur",function(n){var o=a.trim(n.target.value);if(b.getDefault("price")!==o){r(o);a.each(h.query(".J_MapPrice"),
function(p){if(a.trim(p.value)===""){var t=h.attr(p,"data-id");t=b.getCombo(t);p.value=o;t.price=o}});b.updatePrice(o)}});r(a.trim(m.value))},bindQuantity:function(m){f.on("quantityChanged",function(){var r=b.getCombo(),n=0;a.each(b.getRender().list,function(o){n+=r[o.id].quantity*1||0});m.value=n})},hasSaved:function(){u();var m=true;a.each(b.getGroups(),function(r){if(r&&r.type=="CustomGroup"&&!r.hasSaved()){m=false;j=r;return false}});return m},showUnsavedTip:function(){Atpanel.send("http://www.atpanel.com/tbsell.100.2",
{valid:false});j&&j.focus();alert("\u60a8\u6dfb\u52a0\u7684\u9500\u552e\u5c5e\u6027\u6709\u6570\u636e\u672a\u4fdd\u5b58\uff0c\u8bf7\u4fdd\u5b58\u540e\u91cd\u65b0\u63d0\u4ea4\u3002")},expandColors:function(){a.each(b.getGroups(),function(m){if(m&&m.type=="CustomGroup"&&!m.hasSaved()){isSaved=false;j=m;return false}})}}},{requires:["./officialgroup","./customgroup","./imagetable","./combotable","./datacenter"]});
KISSY.add("itempub/sku",function(a,v){var s=a.DOM;return{init:function(){var w=s.get("#J_SellProperties");if(w){var f=s.html("#J_SKUConfig");f=a.trim(f)?a.JSON.parse(f):{};var b=s.get("#J_AddCustomSKU"),i=s.get("#buynow"),e=s.get("#quantityId"),d=s.get("#J_AvailableCustomCPV");b&&v.bindAddGroup(b,w,f.config);d&&v.bindAvaialCPVS(d);e&&v.bindQuantity(e);i&&v.bindPrice(i);v.init(w,f)}},valid:function(){return v.hasSaved()},showTip:function(){v.showUnsavedTip()},expandColors:function(){v.expandColors()}}},
{requires:["./sku/manager"]});KISSY.add("js/publish",function(a){var v=a.makeArray(arguments);a.ready(function(){for(var s=1;s<v.length;s++){var w=v[s]||{};w.init&&w.init()}})},{requires:["./itempub/upload/imgspace.css","./itempub/upload/itempic.css","./itempub/upload/uploadspace.css","./itempub/sku/sku.css","itempub/upload/itempic","itempub/sku"]});
